parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): 'http://127.0.0.1:80'

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        # so the pdo_driver knows which implementation for the pdo interface to use ...
        # since i'm not using the default implementation which lays in /var/mysql/mysql.sock
        unix_socket: '%env(resolve:PDO_IMPLEMENTATION_PATH)%'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Recipe:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domains/Recipe/DomainLayer/Entity'
                prefix: 'App\Domains\Recipe\DomainLayer\Entity'
                alias: Recipe
            RecipeIngredient:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domains/Recipe/DomainLayer/Entity'
                prefix: 'App\Domains\Recipe\DomainLayer\Entity'
                alias: RecipeIngredient
            Step:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domains/Recipe/DomainLayer/Entity'
                prefix: 'App\Domains\Recipe\DomainLayer\Entity'
                alias: Step
            Ingredient:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domains/Core/Entity'
                prefix: 'App\Domains\Core\Entity'
                alias: Ingredient
